Repository VitaCheck/vitacheck-be, pull requests merged in 2025-07, with the labels that each got.

#11 feat(#9):Swagger 기본 설정
  build.gradle
  src/main/java/com/vitacheck/config/SecurityConfig.java
  src/main/java/com/vitacheck/config/SwaggerConfig.java
Labels: ✨ feature

#13 docs(#12): UserController에 Swagger 문서화 추가
  build.gradle
  src/main/java/com/vitacheck/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/vitacheck/config/SecurityConfig.java
  src/main/java/com/vitacheck/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vitacheck/config/jwt/JwtUtil.java
  src/main/java/com/vitacheck/controller/UserController.java
Labels: 📚 docs, ♻️ refactor, 🟩 P4-Low, 👀 needs-review

#22 feat(#21): 모든 목적 ENUM 정의 및 모든 목적 반환 GET API 설계
  src/main/java/com/vitacheck/controller/PurposeController.java
  src/main/java/com/vitacheck/domain/purposes/AllPurpose.java
  src/main/java/com/vitacheck/dto/AllPurposeDto.java
  src/main/java/com/vitacheck/service/PurposeService.java
Labels: ✨ feature

#31 feat: 테스트용 application.yml 파일 추가
  src/main/resources/application-local.yml.example
  src/main/resources/application.yml
Labels: ✨ feature

#33 fix: application.yml 수정
  src/main/resources/application.yml
Labels: ♻️ refactor

#34 fix: application.yml 수정
  src/main/resources/application.yml
Labels: ♻️ refactor

#26 feat(#25):조합 API 기본 구조 작성
  src/main/java/com/vitacheck/controller/CombinationController.java
  src/main/java/com/vitacheck/domain/Combination/Combination.java
  src/main/java/com/vitacheck/domain/Combination/RecommandType.java
  src/main/java/com/vitacheck/dto/CombinationDTO.java
  src/main/java/com/vitacheck/repository/CombinationRepository.java
  src/main/java/com/vitacheck/service/CombinationService.java
Labels: ✨ feature

#30 refactor(#29): GET Purposes API swagger 설명 보강
  src/main/java/com/vitacheck/controller/PurposeController.java
Labels: 📚 docs, ♻️ refactor, 🟩 P4-Low

#41 refactor(#40): 응답 및 예외 처리 구조 통일
  src/main/java/com/vitacheck/config/GlobalExceptionHandler.java
  src/main/java/com/vitacheck/config/SecurityConfig.java
  src/main/java/com/vitacheck/config/oAuth/OAuth2SuccessHandler.java
  src/main/java/com/vitacheck/controller/CombinationController.java
  src/main/java/com/vitacheck/controller/LikeRestController.java
  src/main/java/com/vitacheck/controller/PurposeController.java
  src/main/java/com/vitacheck/controller/TestController.java
  src/main/java/com/vitacheck/controller/UserController.java
  src/main/java/com/vitacheck/exception/CustomException.java
  src/main/java/com/vitacheck/exception/ErrorCode.java
  src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java
  src/main/java/com/vitacheck/service/FoodSafetyApiService.java
  src/main/java/com/vitacheck/service/LikeCommandService.java
  src/main/java/com/vitacheck/service/UserService.java
Labels: ♻️ refactor, 👀 needs-review

#43 feature(#42): AWS 세팅
  .gitignore
  build.gradle
  src/main/java/com/vitacheck/config/AwsS3Config.java
  src/main/java/com/vitacheck/dto/OAuthAttributes.java
  src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java
  src/main/java/com/vitacheck/service/S3UploadService.java
  src/main/resources/application-prod.yml
  src/test/java/com/vitacheck/VitacheckBeApplicationTests.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 🧹 chore, 👀 needs-review

#49 feat(#48): 내 영양제 복용 루틴 등록 API 설계
  src/main/java/com/vitacheck/controller/LikeController.java
  src/main/java/com/vitacheck/controller/NotificationRoutineController.java
  src/main/java/com/vitacheck/domain/NotificationRoutine.java
  src/main/java/com/vitacheck/domain/RoutineDay.java
  src/main/java/com/vitacheck/domain/RoutineDayOfWeek.java
  src/main/java/com/vitacheck/domain/RoutineTime.java
  src/main/java/com/vitacheck/dto/RoutineRegisterRequestDto.java
  src/main/java/com/vitacheck/dto/RoutineRegisterResponseDto.java
  src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java
  src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java
  src/main/java/com/vitacheck/repository/RoutineDayRepository.java
  src/main/java/com/vitacheck/repository/RoutineTimeRepository.java
  src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
Labels: ✨ feature, 👀 needs-review

#52 feat(#51): 내 복용 루틴 목록 조회 API 설계
  src/main/java/com/vitacheck/controller/NotificationRoutineController.java
  src/main/java/com/vitacheck/dto/RoutineResponseDto.java
  src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java
  src/main/java/com/vitacheck/service/RoutineQueryService.java
Labels: ✨ feature, 👀 needs-review

#58 docs: application-test.yml 수정
  src/test/resources/application-test.yml
Labels: 📚 docs

#60 docs: application-prod.yml 수정
  src/main/resources/application-prod.yml
Labels: 📚 docs

#61 docs: application-prod.yml 수정
  src/main/resources/application-prod.yml
Labels: 📚 docs

#72 feat(#71): 알림설정 엔티티 구현 및 로직 변경
  src/main/generated/com/vitacheck/domain/QBrand.java
  src/main/generated/com/vitacheck/domain/QLike.java
  src/main/generated/com/vitacheck/domain/QRoutineDay.java
  src/main/generated/com/vitacheck/domain/QRoutineTime.java
  src/main/generated/com/vitacheck/domain/QSupplement.java
  src/main/generated/com/vitacheck/domain/combination/QCombination.java
  src/main/generated/com/vitacheck/domain/common/QBaseTimeEntity.java
  src/main/generated/com/vitacheck/domain/mapping/QSupplementIngredient.java
  src/main/generated/com/vitacheck/domain/notification/QNotificationRoutine.java
  src/main/generated/com/vitacheck/domain/notification/QNotificationSettings.java
  src/main/generated/com/vitacheck/domain/user/QUser.java
  src/main/java/com/vitacheck/controller/NotificationSettingsController.java
  src/main/java/com/vitacheck/domain/Brand.java
  src/main/java/com/vitacheck/domain/Like.java
  src/main/java/com/vitacheck/domain/RoutineDay.java
  src/main/java/com/vitacheck/domain/RoutineTime.java
  src/main/java/com/vitacheck/domain/Supplement.java
  src/main/java/com/vitacheck/domain/combination/Combination.java
  src/main/java/com/vitacheck/domain/combination/RecommandType.java
  src/main/java/com/vitacheck/domain/common/BaseTimeEntity.java
  src/main/java/com/vitacheck/domain/mapping/SupplementIngredient.java
  src/main/java/com/vitacheck/domain/notification/NotificationChannel.java
  src/main/java/com/vitacheck/domain/notification/NotificationRoutine.java
  src/main/java/com/vitacheck/domain/notification/NotificationSettings.java
  src/main/java/com/vitacheck/domain/notification/NotificationType.java
  src/main/java/com/vitacheck/domain/user/User.java
  src/main/java/com/vitacheck/dto/CombinationDTO.java
  src/main/java/com/vitacheck/dto/NotificationSettingsDto.java
  src/main/java/com/vitacheck/dto/SupplementDto.java
  src/main/java/com/vitacheck/repository/CombinationRepository.java
  src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java
  src/main/java/com/vitacheck/repository/NotificationSettingsRepository.java
  src/main/java/com/vitacheck/repository/SupplementRepositoryImpl.java
  src/main/java/com/vitacheck/service/CombinationService.java
  src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
  src/main/java/com/vitacheck/service/NotificationScheduler.java
  src/main/java/com/vitacheck/service/NotificationSettingsService.java
  src/main/java/com/vitacheck/service/RoutineQueryService.java
  src/test/java/com/vitacheck/service/NotificationSchedulerTest.java
Labels: ✨ feature

#80 Fix(#79): 빌드 환경 표준화 및 FCM 키 관리 개선으로 배포 실패 문제 해결
  build.gradle
  src/main/java/com/vitacheck/config/FirebaseConfig.java
  src/main/java/com/vitacheck/domain/Brand.java
  src/main/java/com/vitacheck/domain/Supplement.java
  src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java
  src/main/resources/application-prod.yml
Labels: 🐛 bug, 👀 needs-review

#81 docs: application-prod.yml 수정
  src/main/resources/application-prod.yml
Labels: 📚 docs

#82 refactor: AwsS3Config 오류 수정
  src/main/java/com/vitacheck/config/AwsS3Config.java
Labels: ♻️ refactor

#83 fix: test용 application 파일 수정
  src/test/java/com/vitacheck/VitacheckBeApplicationTests.java
Labels: ♻️ refactor

#84 docs: ci.yml 파일 수정
  .github/workflows/ci.yml
Labels: 📚 docs

#85 docs: 배포 버그 수정
  .github/workflows/ci.yml
  src/main/resources/application-prod.yml
Labels: 📚 docs

#88 docs: application-prod.yml 수정
  src/main/resources/application-prod.yml
Labels: 📚 docs

#90 fix: amazon s3 관련 문제 수정
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/vitacheck/config/AwsS3Config.java
  src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
  src/main/java/com/vitacheck/service/S3UploadService.java
  src/test/java/com/vitacheck/VitacheckBeApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🐛 bug, ♻️ refactor

#115 fix(#114): JwtAuthenticationFilter 클래스 인증 오류 수정
  src/main/java/com/vitacheck/config/jwt/JwtAuthenticationFilter.java
Labels: 🐛 bug
