Repository VitaCheck/vitacheck-be, pull requests merged in 2025-08, with the labels that each got.

#142 feat(#135): 찜한 성분 조회 API 설계 완료
  src/main/java/com/vitacheck/controller/LikeController.java
  src/main/java/com/vitacheck/dto/LikedIngredientResponseDto.java
  src/main/java/com/vitacheck/repository/IngredientLikeRepository.java
  src/main/java/com/vitacheck/service/IngredientLikeQueryService.java
Labels: ✨ feature, 👀 needs-review

#146 Feature/#145 delete notification routine
  src/main/java/com/vitacheck/controller/NotificationRoutineController.java
  src/main/java/com/vitacheck/domain/notification/NotificationRoutine.java
  src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
Labels: ✨ feature, 👀 needs-review

#152 [FEAT] 특정 브랜드의 다른 영양제 목록 반환 API 제작
  src/main/java/com/vitacheck/controller/SupplementController.java
  src/main/java/com/vitacheck/dto/SupplementDto.java
  src/main/java/com/vitacheck/repository/SupplementRepository.java
  src/main/java/com/vitacheck/service/SupplementService.java
Labels: ✨ feature

#154 [FEAT] 특정 영양제 상세 성분 조회 API 제작
  src/main/java/com/vitacheck/controller/SupplementController.java
  src/main/java/com/vitacheck/dto/SupplementDto.java
  src/main/java/com/vitacheck/repository/IngredientDosageRepository.java
  src/main/java/com/vitacheck/repository/SupplementRepository.java
  src/main/java/com/vitacheck/service/SupplementService.java
Labels: ✨ feature

#157 bug(#156): 로직 수정 완료
  src/main/java/com/vitacheck/controller/NotificationRoutineController.java
  src/main/java/com/vitacheck/service/RoutineQueryService.java
Labels: 🐛 bug, 🔥 P1-Critical, 👀 needs-review

#159 feat(#158): 로직 수정 완료
  src/main/java/com/vitacheck/controller/IntakeRecordController.java
  src/main/java/com/vitacheck/controller/NotificationRoutineController.java
  src/main/java/com/vitacheck/service/IntakeRecordCommandService.java
Labels: ✨ feature, 👀 needs-review

#187 feat(#170): 완료
  src/main/java/com/vitacheck/controller/NotificationRoutineCustomRestController.java
  src/main/java/com/vitacheck/domain/CustomSupplement.java
  src/main/java/com/vitacheck/domain/notification/NotificationRoutine.java
  src/main/java/com/vitacheck/dto/CustomRoutineUpsertRequestDto.java
  src/main/java/com/vitacheck/dto/RoutineResponseDto.java
  src/main/java/com/vitacheck/repository/CustomSupplementRepository.java
  src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java
  src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
  src/main/java/com/vitacheck/service/NotificationRoutineCustomCommandService.java
  src/main/java/com/vitacheck/service/RoutineQueryService.java
Labels: ✨ feature, 🔥 P1-Critical, 👀 needs-review

#215 fix(#214): purposes에 불필요한 필드 (displayOrder, imageUrl, createdAt, updatedAt…
  src/main/java/com/vitacheck/domain/purposes/PurposeCategory.java
Labels: ♻️ refactor, 🧹 chore

#248 fix(#245): 목적별 영양소의 영양제 반환 API 페이지네이션 추가, N+1 수정
  src/main/generated/com/vitacheck/domain/QBrand.java
  src/main/generated/com/vitacheck/domain/QIngredient.java
  src/main/generated/com/vitacheck/domain/QIntakeRecord.java
  src/main/generated/com/vitacheck/domain/QLike.java
  src/main/generated/com/vitacheck/domain/QRoutineDay.java
  src/main/generated/com/vitacheck/domain/QRoutineTime.java
  src/main/generated/com/vitacheck/domain/QSupplement.java
  src/main/generated/com/vitacheck/domain/combination/QCombination.java
  src/main/generated/com/vitacheck/domain/common/QBaseTimeEntity.java
  src/main/generated/com/vitacheck/domain/mapping/QIngredientCategory.java
  src/main/generated/com/vitacheck/domain/mapping/QSupplementIngredient.java
  src/main/generated/com/vitacheck/domain/notification/QNotificationRoutine.java
  src/main/generated/com/vitacheck/domain/notification/QNotificationSettings.java
  src/main/generated/com/vitacheck/domain/purposes/QPurposeCategory.java
  src/main/generated/com/vitacheck/domain/user/QUser.java
  src/main/java/com/vitacheck/controller/SupplementController.java
  src/main/java/com/vitacheck/dto/IngredientPurposeBucket.java
  src/main/java/com/vitacheck/dto/PurposeIngredientSupplementRow.java
  src/main/java/com/vitacheck/repository/IngredientDosageRepository.java
  src/main/java/com/vitacheck/repository/PurposeQueryRepository.java
  src/main/java/com/vitacheck/repository/PurposeQueryRepositoryImpl.java
  src/main/java/com/vitacheck/repository/SupplementRepository.java
  src/main/java/com/vitacheck/service/SupplementService.java
Labels: 🐛 bug

#299 [BUG#298] 내 알림 설정 변경 api 오류 수정
  src/main/java/com/vitacheck/controller/NotificationSettingsController.java
  src/main/java/com/vitacheck/service/NotificationSettingsService.java
Labels: 🐛 bug

#304 [REFRACTOR] 인기 검색 성분 조회 api url 수정(미로그인도 접근 가능)
  src/main/java/com/vitacheck/controller/IngredientController.java
Labels: ♻️ refactor

#323 [REFRACTOR#322] 배포 브랜치 변경 ( deploy → main)
  .github/workflows/ci.yml
Labels: ♻️ refactor
